#!/bin/bash -l

# Set working directory to home directory
cd "${HOME}"

# Restore the module environment to avoid conflicts
module restore

#
# Launch Fluxbox
#

FLUXBOX_RC_FILE="${PBS_O_WORKDIR}/${PBS_JOBID}.rc"
FLUXBOX_ASSETS_ROOT="${ROOT}/fluxbox"

# Build Fluxbox init file
cat > "${FLUXBOX_RC_FILE}" << EOT
session.screen0.toolbar.widthPercent: 60
session.menuFile: $FLUXBOX_ASSETS_ROOT/menu
session.keyFile: $FLUXBOX_ASSETS_ROOT/keys
EOT

# Export the module function for the terminal
[[ $(type -t module) == "function" ]] && export -f module

# Start the Fluxbox window manager
fluxbox -display "${DISPLAY}.0" -rc "${FLUXBOX_RC_FILE}" &

#
# Start Abaqus
#

# Load the Abaqus module
module load ${ABAQUS_MODULE}

# Launch Abaqus
if [[ ${GPU_OFF} ]]; then
  abaqus cae -mesa
else
  module load virtualgl
  vglrun abaqus cae
fi

# Kill vncserver when user closes GUI
vncserver -kill ${DISPLAY}
