title: 'Abaqus/CAE'
compute:
  - &abaqus
    name: 'Abaqus/CAE 6.14 (Software Rendering)'
    batch: 'oakley'
    node: &software_nodes
      - type: 'any'
        ppn: 12
        desc: >
          Choose any type of compute node. This reduces the wait time
          as there are no node specific requirements.
      - type: 'bigmem'
        ppn: 12
        desc: >
          This node has 192GB of available RAM. There are only 8 of
          these nodes on Oakley.
      - type: 'hugemem'
        ppn: 32
        desc: >
          This node has 1TB of available RAM as well as 32 cores.
          There is only 1 of these nodes on Oakley. A reservation may
          be required to use this node.
    pbs:
      envvars:
        ABAQUS_MODULE: 'abaqus/6.14'
        GPU_OFF: '1'
      resources: &resources
        software: 'abaqus+#{(5 * (nodes.to_i * node_ppn.to_i) ** 0.422).floor}'
  - <<: *abaqus
    name: 'Abaqus/CAE 6.14 (Hardware Rendering)'
    node: &hardware_nodes
      - title: 'vis'
        type: 'vis:gpus=1'
        ppn: 12
        desc: >
          This node may come with 1 to 2 Nvidia GPUs. Allows for 3D
          visualization software to run as well as CUDA computations.
    pbs:
      envvars:
        ABAQUS_MODULE: 'abaqus/6.14'
      resources: *resources
  - <<: *abaqus
    name: 'Abaqus/CAE 2016 (Software Rendering)'
    node: *software_nodes
    pbs:
      envvars:
        ABAQUS_MODULE: 'abaqus/2016'
        GPU_OFF: '1'
      resources: *resources
  - <<: *abaqus
    name: 'Abaqus/CAE 2016 (Hardware Rendering)'
    node: *hardware_nodes
    pbs:
      envvars:
        ABAQUS_MODULE: 'abaqus/2016'
      resources: *resources
